### PR TITLE
Refactor emails

### PR DESCRIPTION
**Pull request by excid3**

### CODE REVIEW

**Comment by archonic** [comment]
Is there a way to turn certain emails on/off or the turn off the Pay mailer altogether? Stripe has built out their email functionality and it looks like it's possible to configure a layout and let them handle all customer billing emails.

**Comment by excid3** [comment]
Not yet, but that's a good feature to add here.

**Comment by excid3** [comment]
@archonic I should say, you can turn off Pay emails in the config, but not specific ones atm. https://github.com/pay-rails/pay#configuration

**Comment by archonic** [comment]
Ah, thank you. I think a master switch might be all I need. I'll find out in the coming weeks.

**Pull request merged**
