### PR TITLE
Added support for Lemon Squeezy 

### PR DESCRIPTION
**Pull request by deanpcmad**
This PR adds support for Lemon Squeezy, a payment processor that acts as a Merchant of Record. You can see their site here > https://www.lemonsqueezy.com/

Lemon Squeezy are very similar to Paddle's new Billing APIs, which is one of the reasons I started work on adding it :sweat_smile: 

This code was originally written in July, but I've re-based it with the current changes. It still needs some work so I'm marking this as a draft. I also need to update the [Lemon Squeezy Gem](https://github.com/deanpcmad/lemonsqueezy) that I wrote too as I believe there's been some more API updates

See #897.

### CODE REVIEW

**Comment by excid3** [comment]
Dang! 

I know they've introduced the Customer create and update actions which we can take advantage of which will be nice.

**Comment by deanpcmad** [comment]
Oh that's handy! Will try and work on my library tonight then to add those

**Comment by excid3** [comment]
Lemon Squeezy just announced customer portals which will be handy for testing this: https://www.lemonsqueezy.com/features/customer-portal

**Comment by deanpcmad** [comment]
Oh nice, that will certainly make developers lives easier!

**Comment by harrison-broadbent** [comment]
Hey this is amazing! I've just been looking into using `pay` for a project, but not having LemonSqueezy support was a bit blocker. Has there been much progress with testing this and getting it ready to merge?

**Comment by deanpcmad** [comment]
Hey @harrison-broadbent, your Rails tools are great btw!

I haven't had chance to work more on this yet. I originally started work on it in July as I was thinking about potentially moving from Paddle to them, but then Paddle launched their new Billing APIs 😅 

I'm not sure if I'll get the time to work on it before the new year, but when I get time to update the Ruby wrapper I built, I'll work on this integration too. I could do with tidying up a lot of the commits too, so I may just start from scratch and copy over from the Paddle Billing code, as there's been quite a few changes since my first commits back in July!

**Comment by harrison-broadbent** [comment]
@deanpcmad thanks for the update! And thanks for the kind words!

No stress, a lemon squeezy integration would be amazing though and I'm super keen for it! 
Keep me posted on updates and I'll keep an eye out on any updates from you. Thanks! 👍

**Comment by deanpcmad** [comment]
Closing this as I'm going to start from scratch 😅

**Pull request closed without merging**
