### PR TITLE
Stripe 11.x

### PR DESCRIPTION
**Pull request by henrikbjorn**
Upgrade Stripe gem to `~> 11.0`

**Checklist:**

- [x] Code follows the project's coding standards
- [x] Tests have been added or updated to cover the changes
- [ ] Documentation has been updated (if applicable)
- [ ] All existing tests pass
- [ ] Conforms to the contributing guidelines

### CODE REVIEW

**Comment by excid3** [comment]
The pay/stripe.rb file needs to be updated to require Stripe v11 as well.

**Comment by excid3** [comment]
The `.lock` files need to updated as well.

**Comment by henrikbjorn** [comment]
Ran `bundle exec appraisal install` and it did the last updates

**Comment by excid3** [comment]
That should do the trick. 🤞 
Thanks for the PR!

**Comment by henrikbjorn** [comment]
@excid3 Possible to get a new release cut? :)

**Comment by deanpcmad** [comment]
Chris is currently at RailsConf, so likely later this week

**Pull request merged**
