### PR TITLE
Ensure that data columns are activerecord stores

### LINKED ISSUE #425: MariaDB doesn't not support JSON type. Undefined method 'accessor'
I've just tried to set Pay v3 up on my Rails application (and I've also created a basic Rails app to test this error) but I'm running into issues.

```ruby
customer = Customer.create email: "test@test.com
customer.set_payment_processor :stripe

customer.payment_processor
#<Pay::Customer id: 1, owner_type: "Customer", owner_id: 1, processor: "stripe", processor_id: nil, default: true, data: nil, deleted_at: nil, created_at: "2021-09-08 12:56:25.966822000 +0000", updated_at: "2021-09-08 12:56:25.966822000 +0000", plan: nil, quantity: nil, payment_method_token: nil>

customer.payment_processor.customer
# NoMethodError (undefined method `accessor' for #<ActiveRecord::Type::Text:0x00005634e2aebd08>)
```

When using the Fake Processor, it works fine:

```ruby
Customer.first.set_payment_processor :fake_processor, allow_fake: true
#<Pay::Customer id: 2, owner_type: "Customer", owner_id: 1, processor: "fake_processor", processor_id: "c3X0samQM26S1uBaKBYVy", default: true, data: nil, deleted_at: nil, created_at: "2021-09-08 12:58:06.764957000 +0000", updated_at: "2021-09-08 13:00:20.902029000 +0000", plan: nil, quantity: nil, payment_method_token: nil>

Customer.first.payment_processor.customer
#<Pay::Customer id: 2, owner_type: "Customer", owner_id: 1, processor: "fake_processor", processor_id: "c3X0samQM26S1uBaKBYVy", default: true, data: nil, deleted_at: nil, created_at: "2021-09-08 12:58:06.764957000 +0000", updated_at: "2021-09-08 13:00:20.902029000 +0000", plan: nil, quantity: nil, payment_method_token: nil>
```

I'm using Rails 6.1.4.1 with MariaDB 10.5.12. I've also tried MariaDB 10.6.4.

Any ideas?

### PR DESCRIPTION
**Pull request by excid3**
Fixes MariaDB or other databases where the `data` column is `text` instead of `json`.

Fixes #425

### CODE REVIEW

**Comment by excid3** [comment]
@deanpcmad do you know if we must set a default value for MariaDB json columns? 

```bash
Mysql2::Error: CONSTRAINT `pay_charges.data` failed for `test`.`pay_charges`
```

Seeing this in the test, but setting a default value for CI is going to need to be compatible with all the DBs... 🤪

**Comment by deanpcmad** [comment]
It sure tbh as I've never used the JSON support 😅

On 9 September 2021 16:26:25 Chris Oliver ***@***.***> wrote:
>
> @deanpcmad do you know if we must set a default value for MariaDB json
 columns?
> Mysql2::Error: CONSTRAINT `pay_charges.data` failed for
 `test`.`pay_charges`

**Comment by excid3** [comment]
I got close, but there still appears to be some things that don't work correctly.

I'm out of time to work on this today, but if someone wants to take a stab at finishing this that would be great!

**Comment by deanpcmad** [comment]
Just wondering how this is going?

**Comment by excid3** [comment]
I don't have time to jump to work on this anymore. Anyone else is welcome to finish this up.

**Pull request closed without merging**
