### PR TITLE
Remove extra currencies

### PR DESCRIPTION
**Pull request by olimart**
No need for gold, silver, and other currencies meant for testing purpose

### CODE REVIEW

**Comment by olimart** [comment]
@excid3 if you could please approve running workflow 🙏

**Comment by excid3** [comment]
We're using the Money gem's currency json file, so I'm not too worried about including gold, silver, etc. Just want to make sure this is easy to update.

We can remove it, but it'll likely get added back in the future when we sync changes from the Money gem.

**Comment by olimart** [comment]
@excid3 up to you, I saw that you rely on this file for Jumpstart therefore exposing these options on the UI.
No hard feelings if you decide to close it ;)

**Comment by excid3** [comment]
Yeah, it helps let us render currencies without fully pulling in Money. I think I'll just close this for now.

**Pull request closed without merging**
