### PR TITLE
Updating docs to fill gaps for AddFieldsToBillable migration

### LINKED ISSUE #140: Documentation is slightly outdated?
There seems to be a mismatch between documentation and actual functionality. Initial `bin/rails pay:install:migrations` command created 4 migrations, but documentation suggests that it should be 3.

Adding extra 'AddFieldsToBillable.rb' to the list of new migrations.

Content of this migration is really interesting, it creates additional columns for billable table and how to change it. 

Seems like documentation is slightly outdated. But it's a really important part of documentation as it seems.

### PR DESCRIPTION
**Pull request by skatkov**
I'm currently going through the installation process and trying to update documentation according to actual behavior. 

Hopefully, this fixes #140

### CODE REVIEW

**Comment by excid3** [comment]
This may be a great time to question if we need the readme to include these specifics? Maybe we should just remove these notes since the migrations are likely to change in the future.

**Comment by skatkov** [comment]
@excid3 great suggestion. I removed list of migration files.

**Comment by oleingemann** [comment]
Please continue your work @skatkov , the current docs are terrible. Lost 2 hours now on misc errors, not even getting through rake db:migrate 🥴

**Comment by skatkov** [comment]
@oleingemann would love it if you contribute too -- I'm in a middle of a process myself :P

**Comment by skatkov** [comment]
I think I'm done with this. Can we merge @excid3 ?

**Comment by excid3** [comment]
Sorry it took me so long. Had some family stuff going on unfortunately. ☹️

**Pull request merged**
